spring:
  datasource:
    # 一号数据源
    primary:
      url: jdbc:h2:tcp://127.0.0.1/C:/Users/THINK/Desktop/temp/primary
      username: AAA
      driver-class-name: org.h2.Driver
      # 二 号数据源
    secondary:
      url: jdbc:h2:tcp://127.0.0.1/C:/Users/THINK/Desktop/temp/secondary
      username: BBB
      driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate.hbm2ddl.auto: create
